language: go

go:
  - 1.3
  - 1.4
  - tip

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/yext/revel/revel
  - go get -v github.com/0x19/gotostruct

script:
  - revel test github.com/0x19/jsonstruct.com
